query levels($input: FromQuality) {
          levels(fromQuality: $input, first: 90,after: \"UzIwNjcyMDQyNg==\",) {
            totalCount
            pageInfo {
              hasNextPage
              hasPreviousPage
              startCursor
              endCursor
            }
            edges {
              cursor
              node {
                ... on TxtValue {
                  level
                }
              }
            }
          }
        }
