name: Build and push docker image

on:
  # Turn off the auto-update of the Digital Ocean instance
  # This prevents ongoing development of the UI from impacting Lucivia.net
  # push:
    # paths:
      # - 'Dockerfile'
      # - 'nginx.conf'
      # - 'package.json'
      # - 'src/**'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          IMAGE_ID=ghcr.io/lucivia/frontend:$GITHUB_RUN_ID
          LATEST=ghcr.io/lucivia/frontend:latest
          docker build . -t $IMAGE_ID
          docker image tag $IMAGE_ID $LATEST
          docker push $IMAGE_ID
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DIGITALOCEAN }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
        
      - name: Update kube
        run: ssh root@${{ secrets.DO_HOST }} ./kubectl apply -f kubernetes-all.yaml
