name: deploy-ui

on:
  push:
    paths:
      - '.env-kube'
      - 'Dockerfile.kube'
      - 'src/**'
      - 'package.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE_ID=ghcr.io/lucivia/frontend:$GITHUB_RUN_ID
          RUN_LATEST=ghcr.io/lucivia/frontend:latest
          docker buildx build \
            --file Dockerfile.kube \
            --cache-to type=gha,mode=max \
            --cache-from type=gha \
            --tag $IMAGE_ID \
            --tag $RUN_LATEST \
            --push .

      - name: Push to Digital Ocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: |
          doctl kubernetes cluster kubeconfig save dj-cluster &&
          kubectl rollout restart deployment frontend-deployment -n ingress-nginx
        continue-on-error: true
