name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          IMAGE_ID=ghcr.io/lucivia/frontend:$GITHUB_RUN_ID
          LATEST=ghcr.io/lucivia/frontend:latest
          docker build . --file Dockerfile --tag $IMAGE_ID
          docker image tag $IMAGE_ID $LATEST
          docker push $IMAGE_ID
