name: Docker Kube Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Github registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Kube Docker image

      run: |
          IMAGE_ID=ghcr.io/lucivia/frontend:$GITHUB_RUN_ID
          LATEST=ghcr.io/lucivia/frontend:kube
          docker build . --file Dockerfile.kube --tag $IMAGE_ID
          docker image tag $IMAGE_ID $LATEST
          docker push $IMAGE_ID
          docker push $LATEST
