name: Docker Kube Image CI

on:
  push:
    paths:
      - 'Dockerfile.kube'
      - 'src/**'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Actions
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Kube Docker image
        run: |
          IMAGE_ID=ghcr.io/lucivia/frontend:$GITHUB_RUN_ID
          docker buildx build \
          --file Dockerfile.kube \
          --cache-to type=gha,mode=max \
          --cache-from type=gha \
          --tag $IMAGE_ID \
          --push .
          # docker buildx image tag $IMAGE_ID $LATEST
          # docker buildx push $LATEST
